### ISSUE TITLE
List installed, available, search by repo 

### ISSUE THREAD

**Issue by biji** [timlau/yumex-dnf#127] opened 2016-06-21 16:56 UTC
Please add feature to list installed, available, search from a repo only

**Comment by genodeftest** [comment] 2016-06-24 22:56
I don't understand what you mean. Can you please explain it?

Do you mean something like #89 ?

**Comment by biji** [comment] 2016-06-25 00:55
Yes, similiar to #89

Equivalent command is:
`dnf repo-pkgs REPO list`
`dnf repo-pkgs REPO list installed`
`dnf repo-pkgs REPO search STRING`

**Comment by genodeftest** [comment] 2016-06-25 09:09
Closing as duplicate of #89 and suggestions in #74 then.

**Closed as completed by genodeftest** 2016-06-25 09:09 UTC
Labels: duplicate, RFE, UI
