### ISSUE TITLE
[User Experience] Don't change Type when deleting search entry text or adding search entry text

### ISSUE THREAD

**Issue by genodeftest** [timlau/yumex-dnf#54] opened 2015-09-18 20:39 UTC
Steps to reproduce:
1. search for any term
2. change the type to e.g. "All"
3. delete the search term using the "delete" icon

What happens:
Yumex-dnf changes type to "Update". There is no indicator that it did.

What should happen:
yumex-dnf should not change the type

Steps to reproduce:
1. change the type to e.g. "Update"
2. search for any term

What happens:
Yumex-dnf changes type to "All". There is no indicator that it did.

What should happen:
yumex-dnf should not change the type

Affected version: yumex-dnf-4.1.3-1.fc22.noarch

**Comment by rapgro** [comment] 2015-09-19 08:43
I can reproduce this. It's a strange impression to the user how the search should work correctly.

**Comment by timlau** [comment] 2015-10-01 13:49
Yumex has 2 modes.

a. browse mode: you can browse packages based on type (installed, updates, available or all)
b. search mode: you can search for packages matching a search term and browse the result based on type (installed, updates, available or all)


*Usecase:*
 If you want to find something you do the following.

1.  start yumex-dnf (default filter is updates)
2.  type search pattern
3.  yumex will show **all** packages matching the search pattern and the filter changes to **All**
4.  you can reduce the search result by changing the filter to "updates, available or installed"
5. When you clear the search, then yumex jumps back to browse mode restoring the filter from before the search.

The problem is that show all packages in browse mode is slow, because of the number of packages in Fedora and GTK is slow when population a TreeView with a lot of elements.
So there is 2 kind of package type filter, one in browse mode (default = updates) and on in search mode (default=all)

**Comment by genodeftest** [comment] 2015-10-01 21:09
I guess this 2-mode-behaviour is not what people expect. When I am setting a filter (by type) or a search option I expect that to stay this way, except
a. I change it
b. I am notified that it is being changed

In this case you chose b., but the notification (in a hidden menu) is too weak. I won't look into the "main menu" every time I did some action. Applications changing their options automatically without notifying the user tend to frustrate them. As long as an option is present, I expect yumex to respect it. Your usecase is good in theory but fails on the user in practice.

I'm working on some mockups to propose some UI/UX changes for yumex, but I don't have something presentable yet.

**Comment by timlau** [comment] 2015-10-05 14:11
I agree, there is room for improvement in the UI/UX in yumex, thanks for your feedback

**Comment by timlau** [comment] 2015-12-01 14:13
This one should be fixed in current redesigned development version, so I will close it

**Closed by timlau** 2015-12-01 14:13 UTC
Labels: UI
