### ISSUE TITLE
everytime it's launched, the window is taller than previous launch by the height of the 'getting updates' progress bar section

### ISSUE THREAD

**Issue by kn00tcn** [timlau/yumex-dnf#148] opened 2017-01-17 02:34 UTC
i think this has been going on since fedora 23's version if it's distro specific (in mate for sure, i forgot it xfce does it, didnt check enlightenment before uninstalling that, havent tried gnome or kde or cinnamon to confirm those either)

i basically have to resize it almost every time, although it seems to stop enlarging once it goes near the monitor's resolution at this point (f25)

for more awkwardness, try with the horizontal pane divider dragged to its max top compared to in the middle or bottom

if i alter the repo list, the window size might be the same, but the top pane gets enlarged (divider moves down)

good solution: the progressbar shouldnt be an actual inline element, it should be some kind of overlay or popup (like the prefs screen), maybe aligned more in the center both vertically & horizontally

cheap solution: dont push content below or resize the window back down after the progress bar is shown

**Comment by genodeftest** [comment] 2017-01-18 14:49
Thanks for the bug report, I can confirm this happens.

Easiest steps to reproduce:
1. open yumex-dnf
2. resize it to be as small as possible
3. close yumex-dnf
4. open yumex-dnf
Now the window size has increased quite a bit.

> good solution: the progressbar shouldnt be an actual inline element, it should be some kind of overlay or popup (like the prefs screen), maybe aligned more in the center both vertically & horizontally

Do you mean in a different (sub-)window such as a dialog? I'm opposed to this, because it is against modern UX guidelines to have dialogs (except where absolutely necessary).
I also thought about using a [GtkOverlay](https://developer.gnome.org/gtk3/3.22/GtkOverlay.html) when designing the current situation, but this will prevent users from interacting with parts of the GUI while the repos load.

> cheap solution: dont push content below or resize the window back down after the progress bar is shown

I'd rather expect this to be the default behavior of a GtkRevealer. Anyway, I just noticed that we are using a GtkRevealer inside a GtkRevealer, which sounds pretty wrong.
Not hiding the progress bar when no progress state is known looks like the better solution to me.

**Comment by genodeftest** [comment] 2017-01-18 14:57
By the way, the official repo version also has a bug fixed by commit d89dda5a7432076fd7ca7feee2573ab8f16290a7.

**Comment by kn00tcn** [comment] 2017-01-19 01:48
but i cant interact with the ui during that time, the tabs are greyed & the mouse cursor is a loading icon

maybe not an actual popup with window decorations & shadows, but some kind of overlay thing... http://www.jqueryscript.net/images/jQuery-Plugin-For-Creating-Loading-Overlay-with-CSS3-Animations-waitMe.jpg

another cheap solution is the same visual progress section, but it's a dropdown that covers the top of the main area's columns (like OSX's dialogs? http://cdn.osxdaily.com/wp-content/uploads/2014/12/SHRINK-SAVE-DIALOG-WINDOW-OS-X.jpg ignore the red highlight)

edit: i find it quite interesting that the window stops getting larger once it nears the monitor's height, i expected it to keep going, maybe it did in f23 but i dont remember now, plus maximized is unaffected although maybe that's for the same reason

**Comment by timlau** [comment] 2021-06-29 12:37
The current release keep the windows size.

**Closed as completed by timlau** 2021-06-29 12:37 UTC
Labels: bug, UI
